const hunterPrideInterviewData = [
    {
        fieldReviewId: 1,
        title: "헌터 도입 후 달라진 우리 정비소",
        contentSummary: "헌터 장비 도입 후 정비의 정확도와 고객 만족도가 함께 높아졌습니다. 고객이 믿고 맡길 수 있는 정비 환경을 만들어가는 이야기를 확인해보세요.",
        reviewerName: "대영오토모터스",
        publishedAt: "2026.07.07",
        thumbnailUrl: "/images/sub_p_p01.png",
        videoUrl: "https://youtu.be/tlcEurH9Cpg?si=gLSgzMjAznvcH2hA",
        exposureType: "FEATURED",
        isExposed: true,
        displayOrder: 1
    },
    {
        fieldReviewId: 2,
        title: "성공적인 정비소 운영의 파트너",
        contentSummary: "정확한 측정 데이터와 빠른 작업 흐름을 통해 정비 품질과 작업 효율을 함께 높인 현장의 이야기를 소개합니다.",
        reviewerName: "헌터 강남 서비스센터",
        publishedAt: "2026.07.07",
        thumbnailUrl: "/images/sub_p_p02.png",
        videoUrl: "https://youtu.be/SgUbLVfzr28?si=pihm_IV4BTEoDOSI",
        exposureType: "FEATURED",
        isExposed: true,
        displayOrder: 2
    },
    {
        fieldReviewId: 3,
        title: "고객 신뢰를 만든 헌터 솔루션",
        contentSummary: "헌터 솔루션을 바탕으로 고객에게 더 정확하고 신뢰할 수 있는 정비 서비스를 제공하는 현장을 만나보세요.",
        reviewerName: "헌터 수원 서비스센터",
        publishedAt: "2026.07.07",
        thumbnailUrl: "/images/sub_p_p03.png",
        videoUrl: "https://youtu.be/sl1relqfdyU?si=au7fnBZFrwQxa7uf",
        exposureType: "FEATURED",
        isExposed: true,
        displayOrder: 3
    },
    {
        fieldReviewId: 4,
        title: "정확한 진단이 만든 새로운 기준",
        contentSummary: "장비 도입 이후 달라진 진단 과정과 고객 상담 방식에 대한 실제 현장 인터뷰입니다.",
        reviewerName: "헌터 인천 서비스센터",
        publishedAt: "2026.07.07",
        thumbnailUrl: "",
        videoUrl: "https://youtu.be/sl1relqfdyU?si=au7fnBZFrwQxa7uf",
        exposureType: "FEATURED",
        isExposed: true,
        displayOrder: 4
    },
    {
        fieldReviewId: 5,
        title: "작업 효율을 높인 헌터 장비",
        contentSummary: "작업 시간을 줄이면서도 정비 정확도를 높인 운영 경험을 인터뷰로 확인해보세요.",
        reviewerName: "헌터 대구 서비스센터",
        publishedAt: "2026.07.07",
        thumbnailUrl: "",
        videoUrl: "https://youtu.be/sl1relqfdyU?si=au7fnBZFrwQxa7uf",
        exposureType: "GENERAL",
        isExposed: true,
        displayOrder: 1
    },
    {
        fieldReviewId: 6,
        title: "고객 만족으로 이어진 변화",
        contentSummary: "정확한 데이터와 일관된 작업 품질이 고객 만족으로 이어진 현장의 이야기를 담았습니다.",
        reviewerName: "헌터 부산 서비스센터",
        publishedAt: "2026.07.07",
        thumbnailUrl: "",
        videoUrl: "https://youtu.be/sl1relqfdyU?si=au7fnBZFrwQxa7uf",
        exposureType: "GENERAL",
        isExposed: true,
        displayOrder: 2
    },
    {
        fieldReviewId: 7,
        title: "정비소 경쟁력을 높이는 방법",
        contentSummary: "헌터 장비를 활용해 정비소의 전문성과 경쟁력을 강화한 운영 노하우를 소개합니다.",
        reviewerName: "헌터 광주 서비스센터",
        publishedAt: "2026.07.07",
        thumbnailUrl: "",
        videoUrl: "https://youtu.be/sl1relqfdyU?si=au7fnBZFrwQxa7uf",
        exposureType: "GENERAL",
        isExposed: true,
        displayOrder: 3
    },
    {
        fieldReviewId: 8,
        title: "신뢰받는 정비 환경 만들기",
        contentSummary: "고객에게 측정 결과를 명확하게 설명하고 신뢰를 쌓아가는 실제 사례를 확인해보세요.",
        reviewerName: "헌터 대전 서비스센터",
        publishedAt: "2026.07.07",
        thumbnailUrl: "",
        videoUrl: "https://youtu.be/sl1relqfdyU?si=au7fnBZFrwQxa7uf",
        exposureType: "GENERAL",
        isExposed: true,
        displayOrder: 4
    },
    {
        fieldReviewId: 9,
        title: "헌터와 함께 만든 성장",
        contentSummary: "장비 도입부터 운영 안정화까지, 헌터와 함께 성장한 정비소의 이야기를 전합니다.",
        reviewerName: "헌터 제주 서비스센터",
        publishedAt: "2026.07.07",
        thumbnailUrl: "",
        videoUrl: "https://youtu.be/sl1relqfdyU?si=au7fnBZFrwQxa7uf",
        exposureType: "GENERAL",
        isExposed: true,
        displayOrder: 5
    }
];
